export const lightingProducts = [
  {
    id: "meandra-p-led-54w-black-cct",
    name: "LED Полилей MEANDRA-P LED 54W Черен CCT 3000-4000-6000K",
    category: "interior",
    type: "chandelier",
    mount: "ceiling",
    power: 54,
    color: "черен",
    cct: ["3000K", "4000K", "6000K"],
    voltage: "230V",
    frequency: "50/60Hz",
    ip: "IP20",
    cri: "≥80",
    lifetime: 15000,
    beamAngle: 120,
    flickerFree: true,
    motionSensor: false,
    dimmable: false,
    remoteControl: false,
    price: 110,
    currency: "EUR",
    image: "/images/lighting/interior/chandeliers/meandra-p-led-54w-black-cct.jpg"
  },

  {
    id: "lucas-led-30w-black-wood-cct",
    name: "LED Плафон LUCAS LED 30W Черно + Дърво CCT 3000-4000-6400K",
    category: "interior",
    type: "ceiling",
    mount: "ceiling",
    power: 30,
    color: "черно+дърво",
    cct: ["3000K", "4000K", "6400K"],
    voltage: "230V",
    frequency: "50/60Hz",
    ip: "IP20",
    cri: "≥80",
    lifetime: 15000,
    beamAngle: 120,
    flickerFree: true,
    motionSensor: false,
    dimmable: false,
    remoteControl: false,
    price: 110,
    currency: "EUR",
    image: "/images/lighting/interior/ceiling/lucas-led-30w-black-wood-cct.jpg"
  },

  {
    id: "campo-led-36w-black-white-wood-cct",
    name: "LED Плафон CAMPO LED 36W Черно/Бяло + Дърво CCT 3000-4000-6400K",
    category: "interior",
    type: "ceiling",
    mount: "ceiling",
    power: 36,
    color: "черно/бяло+дърво",
    cct: ["3000K", "4000K", "6400K"],
    voltage: "230V",
    frequency: "50/60Hz",
    ip: "IP20",
    cri: "≥80",
    lifetime: 30000,
    beamAngle: 120,
    flickerFree: true,
    motionSensor: false,
    dimmable: false,
    remoteControl: false,
    price: 140,
    currency: "EUR",
    image: "/images/lighting/interior/ceiling/campo-led-36w-black-white-wood-cct.jpg"
  },

  {
    id: "dorothy-led-74w-cct-remote",
    name: "LED Плафониера DOROTHY LED 74W CCT 3000-6000K с дистанционно",
    category: "interior",
    type: "ceiling",
    mount: "ceiling",
    power: 74,
    cct: ["3000K", "4000K", "6000K"],
    voltage: "230V",
    frequency: "50/60Hz",
    ip: "IP20",
    cri: "≥80",
    lifetime: 15000,
    beamAngle: 120,
    flickerFree: true,
    dimmable: true,
    remoteControl: true,
    motionSensor: false,
    price: 175,
    currency: "EUR",
    image: "/images/lighting/interior/ceiling/dorothy-led-74w-cct-remote.jpg"
  },

  {
    id: "river-led-24w-black-4000k",
    name: "LED Плафон RIVER LED 24W Черен 4000K",
    category: "interior",
    type: "ceiling",
    mount: "ceiling",
    power: 24,
    color: "черен",
    cct: ["4000K"],
    voltage: "230V",
    frequency: "50/60Hz",
    ip: "IP20",
    cri: "≥80",
    lifetime: 20000,
    beamAngle: 120,
    flickerFree: true,
    motionSensor: false,
    dimmable: false,
    remoteControl: false,
    price: 85,
    currency: "EUR",
    image: "/images/lighting/interior/ceiling/river-led-24w-black-4000k.jpg"
  }
];
