export const lightingProducts = [

{
id: "castor-led-5w-ip65-exit",
name: "Аварийно осветително тяло CASTOR LED 5W IP65 EXIT",
marketingText: "Надеждно аварийно осветление с ясно обозначение EXIT и защита IP65. Подходящо за обществени сгради, стълбища и евакуационни изходи при прекъсване на електрозахранването.",
category: "emergency",
type: "exit-sign",
mount: "wall",
power: 5,
battery: "Li-Ion 3.7V 2200mAh",
voltage: "110-240V",
frequency: "50/60Hz",
ip: "IP65",
beamAngle: 120,
flickerFree: true,
motionSensor: false,
dimmable: false,
remoteControl: false,
price: 50,
currency: "EUR",
image: "/images/lighting/emergency/castor-led-5w-ip65-exit.jpg",
},

{
id: "racer-led-m-3w",
name: "Аварийно LED осветително тяло RACER LED-M 3W",
marketingText: "Компактно аварийно осветително тяло с надеждна Li-Ion батерия. Осигурява безопасност и видимост при аварийни ситуации в коридори, стълбища и обществени пространства.",
category: "emergency",
type: "emergency-lamp",
mount: "wall",
power: 3,
battery: "Li-Ion 3.7V 1000mAh",
voltage: "230V",
frequency: "50/60Hz",
ip: "IP20",
beamAngle: 120,
flickerFree: true,
motionSensor: false,
dimmable: false,
remoteControl: false,
price: 35,
currency: "EUR",
image: "/images/lighting/emergency/racer-led-m-3w-emergency.jpg",
},

{
id: "jex-pc-base-222-1200mm",
name: "Индустриално осветително тяло JEX PC BASE 222 LED 1200 mm",
marketingText: "Здраво индустриално осветително тяло с висока защита IP65, подходящо за складове, производствени помещения и гаражи. Осигурява надеждна работа в прашна и влажна среда.",
category: "industrial",
type: "batten",
mount: "ceiling",
length: 1200,
socket: "2xG13",
voltage: "230V",
frequency: "50/60Hz",
ip: "IP65",
price: 45,
currency: "EUR",
image: "/images/lighting/industrial/jex-pc-base-222-1200mm.jpg",
},

{
id: "jex-pc-base-224-1500mm",
name: "Индустриално осветително тяло JEX PC BASE 224 LED 1500 mm",
marketingText: "Устойчиво индустриално осветително тяло с защита IP65 и възможност за монтаж в тежки условия. Идеално решение за халета, складове и работни помещения.",
category: "industrial",
type: "batten",
mount: "ceiling",
length: 1500,
socket: "2xG13",
voltage: "230V",
frequency: "50/60Hz",
ip: "IP65",
price: 55,
currency: "EUR",
image: "/images/lighting/industrial/jex-pc-base-224-1500mm.jpg",
},

{
id: "kent-led-18w-600mm-4000k",
name: "Индустриално LED осветително тяло KENT LED 18W 600mm 4000K",
marketingText: "Компактно и енергийно ефективно индустриално LED осветление с неутрална светлина 4000K. Подходящо за складове, сервизни помещения и коридори.",
category: "industrial",
type: "batten",
mount: "ceiling",
power: 18,
length: 600,
cct: ["4000K"],
voltage: "230V",
frequency: "50/60Hz",
ip: "IP65",
cri: "≥80",
lifetime: 30000,
beamAngle: 120,
price: 35,
currency: "EUR",
image: "/images/lighting/industrial/kent-led-18w-600mm-4000k.jpg",
},

{
id: "kent-led-36w-1200mm-4000k",
name: "Индустриално LED осветително тяло KENT LED 36W 1200mm 4000K",
marketingText: "Мощно индустриално LED осветително тяло с равномерно осветяване и защита IP65. Отличен избор за производствени помещения, складове и работни зони.",
category: "industrial",
type: "batten",
mount: "ceiling",
power: 36,
length: 1200,
cct: ["4000K"],
voltage: "230V",
frequency: "50/60Hz",
ip: "IP65",
cri: "≥80",
lifetime: 30000,
beamAngle: 120,
price: 45,
currency: "EUR",
image: "/images/lighting/industrial/kent-led-36w-1200mm-4000k.jpg",
},

{
id: "kent-led-45w-1500mm-4000k",
name: "Индустриално LED осветително тяло KENT LED 45W 1500mm 4000K",
marketingText: "Високоефективно LED осветление с мощност 45W и защита IP65, предназначено за индустриални и складови пространства, където се изисква силна и надеждна светлина.",
category: "industrial",
type: "batten",
mount: "ceiling",
power: 45,
length: 1500,
cct: ["4000K"],
voltage: "230V",
frequency: "50/60Hz",
ip: "IP65",
cri: "≥80",
lifetime: 30000,
beamAngle: 120,
price: 50,
currency: "EUR",
image: "/images/lighting/industrial/kent-led-45w-1500mm-4000k.jpg",
},

];
